/* Florian Lefèvre, Collection 00 — "Requiem". Edit names, prices and copy here. */
window.HALOGRAVE_PRODUCTS = [
  {
    id: "requiem-jacket",
    name: "Lefèvre biker jacket",
    category: "Outerwear",
    price: 3400,
    image: "images/requiem-jacket.jpg",
    blurb: "Waxed horsehide, hand-distressed at the elbows and hem. The asymmetric zip and belt buckle are cast in oxidized sterling from the broken halo.",
    sizes: ["XS", "S", "M", "L", "XL"],
    feature: true,
  },
  {
    id: "vigil-pendant",
    name: "Lefèvre nail pendant",
    category: "Silver",
    price: 1240,
    image: "images/vigil-pendant.jpg",
    blurb: "The house sigil in solid .925 sterling on a 60 cm hand-linked chain. Heavy enough that you feel it all day.",
    sizes: ["60 cm"],
  },
  {
    id: "ash-veil-hoodie",
    name: "Lefèvre washed hoodie",
    category: "Tops",
    price: 980,
    image: "images/ash-veil-hoodie.jpg",
    blurb: "Heavyweight loopback cotton washed six times until it fades like ash. Dropped shoulders and sleeves cut long enough to swallow the hand.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "martyr-boot",
    name: "Lefèvre platform boot",
    category: "Footwear",
    price: 1850,
    image: "images/martyr-boot.jpg",
    blurb: "Knee-high calf leather on a 9 cm platform sole. Three buckled straps, each buckle cast in sterling.",
    sizes: ["40", "41", "42", "43", "44", "45"],
  },
  {
    id: "sepulchre-cargo",
    name: "Lefèvre drop cargo",
    category: "Bottoms",
    price: 1150,
    image: "images/sepulchre-cargo.jpg",
    blurb: "Drop-crotch cargo in garment-dyed cotton twill with oversized bellowed pockets and drawcords at the waist and ankles.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "broken-halo-ring",
    name: "Lefèvre nail ring",
    category: "Silver",
    price: 890,
    image: "images/broken-halo-ring.jpg",
    blurb: "Hand-hammered sterling, broken open and pierced by a single nail. Left to tarnish, so it darkens the longer you wear it.",
    sizes: ["7", "8", "9", "10", "11", "12"],
  },
  {
    id: "pale-saint-denim",
    name: "Lefèvre flared denim",
    category: "Bottoms",
    price: 1290,
    image: "images/pale-saint-denim.jpg",
    fx: "dark",
    blurb: "14 oz black Japanese selvedge cut to a long flare, torn open at both knees and patched back together with hand stitching.",
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "ossuary-tank",
    name: "Lefèvre long tank",
    category: "Tops",
    price: 420,
    image: "images/ossuary-tank.jpg",
    fx: "dark",
    blurb: "Bias-cut rib jersey with a raw, uneven hem that keeps fraying after you buy it. That is the point.",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
];
